### ISSUE TITLE
screams and cries ingame

### ISSUE THREAD

**Issue by arceuss** [Tiny-Foxes/porting-scripts#1]
![image](https://user-images.githubusercontent.com/28229451/114604094-c3704480-9c55-11eb-8dff-7f27295bd3db.png)

**Comment by Scraticus** [comment]
MungyoDance is not NitG, please read before posting no-context issues.

thanks

This porting script is not even meant for this kind of operation. Mugyodance stuff doesn't even include xml command stuff to convert, and the tool requires a mirin template beforehand to even start the conversion process.

**Comment by Sudospective** [comment]
This has nothing to do with Mungyodance and involves my porting script. I'll look into it.

Can you give more details, such as snippets of your code?

**Comment by Sudospective** [comment]
Closing this issue again; there's not enough info to get started on figuring out the issue.
